name: CI
run-name: Testing your application
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Prisma setup
        run: npx prisma db push --preview-feature
      - name: Start application
        run: npm run dev & sleep 10
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: "http://localhost:3000"
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      - name: Request backend
        run: curl http://localhost:3000/api/auth-test
      - name: Install cypress dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: Run cypress
        run: npx cypress run
        env:
          CYPRESS_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          CYPRESS_GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          CYPRESS_GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          CYPRESS_COOKIE_NAME: next-auth.session-token
          CYPRESS_BASE_URL: http://localhost:3000
