name: CI
run-name: Testing your application
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Run migrations
        run: npx prisma migrate dev
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:54322/postgres
      - name: Cypress run
        uses: cypress-io/github-actions@v3
        with:
          project: ./
          browser: chrome
          build: npm run build
          start: npm run start
          wait-on: "http://localhost:3000"
        env:
          NEXTAUTH_SECRET: ${{ NEXTAUTH_SECRET }}
          NEXTAUTH_URL: "http://localhost:3000"
          GOOGLE_CLIENT_ID: ${{ GOOGLE_ID }}
          GOOGLE_ID: ${{ GOOGLE_ID }}
          GOOGLE_SECRET: ${{ GOOGLE_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ GOOGLE_REFRESH_TOKEN }}
          DATABASE_URL: postgresql://postgres:postgres@localhost:54322/postgres
