name: CI
run-name: Testing your application
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Prisma setup
        working-directory: ./src
        run: npx prisma db push --preview-feature
      - name: Setup env file for prisma
        run: echo DATABASE_URL=postgresql://postgres:postgres@localhost:5432/postgres > .env
      - name: Start application
        run: npm run dev % sleep 10
        env:
          HOST_URL: "localhost"
          HOST_PORT: "3000"
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: "http://localhost:3000"
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_ID }}
          GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          wait-on: "http://localhost:3000"
        env:
          CYPRESS_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_ID }}
          CYPRESS_GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          CYPRESS_GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          CYPRESS_COOKIE_NAME: next-auth.session-token
          CYPRESS_BASE_URL: http://localhost:3000
